### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by Shadowman4205** [yury-dymov/redux-oauth-demo#2]
Trying run it but i get this error and it pause there

**Comment by Shadowman4205** [comment]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3002
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (C:\Test\redux-oauth-demo-master\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:/Test/redux-oauth-demo-master/src/server.js:105:5)
    at Module._compile (module.js:570:32)
    at loader (C:\Test\redux-oauth-demo-master\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Test\redux-oauth-demo-master\node_modules\babel-register\lib\node.js:154:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Shadowman4205** [comment]
ok found i had an app running on 3001
